In [2]:
import numpy as np                          # Numerical Python 
import matplotlib.pyplot as plt             # Python plotting
from PIL import Image                       # Python Imaging Library
import matplotlib.image as image
from numpy.fft import fft, fft2, fftshift, ifft2          # Python DFT
# Show plots in the notebook (don't use it in Python scripts)
%matplotlib inline 
import scipy.fft


In [3]:
from scipy.fftpack import dct, idct


In [4]:
##Q.2. Write python from scratch for computing 2D DFT{X(k,l)} of the following 2D array 
## (a) x(m,n) = np.array([[1, 0],[2, 1]])

In [6]:
#defining func for 2d dft 
def dft_matrix(n):
    F = [[1j*(2*np.pi/n)*p*q for p in range(n)] for q in range(n)]
    E = np.exp(F)
    return E
    

def dft(x):
    dim = x.shape
    X = np.zeros(dim)
    E = dft_matrix(dim[0])
    X = np.matmul(E,x)
    X = np.matmul(X,E)
    return X
    
#giving input 
x = np.array([[1,0],[2,1]])
arr_dft = dft(x)
print(arr_dft)

#by dft package
dft_lib = fft(fft(x, axis=0), axis=1)
print()
print(" by dft lib ",dft_lib )


[[ 4.00000000e+00+0.0000000e+00j  2.00000000e+00+1.2246468e-16j]
 [-2.00000000e+00+3.6739404e-16j -1.49975978e-32+0.0000000e+00j]]

 by dft lib  [[ 4.+0.j  2.+0.j]
 [-2.+0.j  0.+0.j]]


In [7]:
##Q2(b) x(m,n) = np.array([[1,2, 3,4], [5, 6, 7, 8], [9,10,11,12], [13,14,15,16]])

In [9]:
#giving input
x = np.array([[1,2, 3,4], [5, 6, 7, 8], [9,10,11,12], [13,14,15,16]])
arr_dft = dft(x)
print(arr_dft)

dft_using_lib = fft(fft(x, axis=0), axis=1)
print()
print("by dft lib ")
print(dft_using_lib)

[[ 1.36000000e+02+0.00000000e+00j -8.00000000e+00-8.00000000e+00j
  -8.00000000e+00+9.79717439e-15j -8.00000000e+00+8.00000000e+00j]
 [-3.20000000e+01-3.20000000e+01j  5.02228984e-15-2.08313752e-15j
   1.83078039e-16-1.95943488e-15j  9.20342041e-16-6.18508532e-15j]
 [-3.20000000e+01+1.42059029e-14j  1.95943488e-15-2.26621556e-15j
  -9.59846261e-31-2.44929360e-15j -3.12223036e-15-3.15439398e-15j]
 [-3.20000000e+01+3.20000000e+01j -3.06780680e-16-3.24593300e-15j
  -1.95943488e-15-1.95943488e-15j -5.29690690e-15+8.56014798e-16j]]

by dft lib 
[[136. +0.j  -8. +8.j  -8. +0.j  -8. -8.j]
 [-32.+32.j   0. +0.j   0. +0.j   0. +0.j]
 [-32. +0.j   0. +0.j   0. +0.j   0. +0.j]
 [-32.-32.j   0. +0.j   0. +0.j   0. +0.j]]


In [10]:
##Q.3.Write python from scratch for 2D Circular convolution using Doubly Block Circulant matrices method between input=np.array([[1,2,3],[4,5,6],[7,8,9]])and filter=np.array([[1,2,1],[0,0,0],[-1,-2,-1]]) 

In [11]:
# printing input matrix 
Input = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Input matrix', Input.shape)
print(Input)

# printing Filter matrix
Filter = np.array([[1,2,1],[0,0,0],[-1,-2,-1]]) 
print('Filter matrix: ',Filter.shape)
print(Filter)



Input matrix (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Filter matrix:  (3, 3)
[[ 1  2  1]
 [ 0  0  0]
 [-1 -2 -1]]


In [12]:
#Number of Columns and Rows of Input Matrix
Input_row_number, Input_column_number = Input.shape

#Number of Columns and Rows of Filter Matrix
Filter_row_number, Filter_column_number = Filter.shape

Output_Block_matrix_row_number = max(Input_row_number, Filter_row_number)
Output_Block_matrix_column_number = max(Input_column_number, Filter_column_number)
print("Output Block matrix dimensions ", Output_Block_matrix_row_number, Output_Block_matrix_column_number)


Output Block matrix dimensions  3 3


In [21]:
# constructing H0, H1 and H2 matrices
from scipy.linalg import circulant
 
H0 = circulant(Filter[2:3])
print("H0 ", H0)
 
H1 = circulant(Filter[1:2])
print("H1 ", H1)
 
H2 = circulant(Filter[0:1])
print("H2 ", H2)
Row1 = np.hstack([H0, H2, H1])
Row2 = np.hstack([H1, H0, H2])
Row3 = np.hstack([H2, H1, H0])
 
print(Row1)
print(Row2)
print(Row3)
 
Doubly_blockmtrx = np.vstack([Row1, Row2, Row3])
print(Doubly_blockmtrx)

def matrix_to_vector(input):
    input_h, input_w = input.shape
    output_vector = np.zeros(input_h*input_w, dtype=input.dtype)

# flip the input matrix up-down because last row should go first
    input = np.flipud(input) 
    for i,row in enumerate(input):
        st = i*input_w
        nd = st + input_w
        output_vector[st:nd] = row
    return output_vector




H0  [[-1 -1 -2]
 [-2 -1 -1]
 [-1 -2 -1]]
H1  [[0 0 0]
 [0 0 0]
 [0 0 0]]
H2  [[1 1 2]
 [2 1 1]
 [1 2 1]]
[[-1 -1 -2  1  1  2  0  0  0]
 [-2 -1 -1  2  1  1  0  0  0]
 [-1 -2 -1  1  2  1  0  0  0]]
[[ 0  0  0 -1 -1 -2  1  1  2]
 [ 0  0  0 -2 -1 -1  2  1  1]
 [ 0  0  0 -1 -2 -1  1  2  1]]
[[ 1  1  2  0  0  0 -1 -1 -2]
 [ 2  1  1  0  0  0 -2 -1 -1]
 [ 1  2  1  0  0  0 -1 -2 -1]]
[[-1 -1 -2  1  1  2  0  0  0]
 [-2 -1 -1  2  1  1  0  0  0]
 [-1 -2 -1  1  2  1  0  0  0]
 [ 0  0  0 -1 -1 -2  1  1  2]
 [ 0  0  0 -2 -1 -1  2  1  1]
 [ 0  0  0 -1 -2 -1  1  2  1]
 [ 1  1  2  0  0  0 -1 -1 -2]
 [ 2  1  1  0  0  0 -2 -1 -1]
 [ 1  2  1  0  0  0 -1 -2 -1]]


In [22]:
# calling the function
vectorized_Input = matrix_to_vector(Input)
print('vectorized_input: ', vectorized_Input)

result_vector = np.matmul(Doubly_blockmtrx, vectorized_Input)
print('result_vector: ', result_vector)


vectorized_input:  [7 8 9 4 5 6 1 2 3]
result_vector:  [-12 -12 -12 -12 -12 -12  24  24  24]


In [18]:
##Q.4. Write python code to compute 2D DCT for the 4x4 image S given below and reconstruct it using different masking windows to evaluate the effect of different basis images. 
##1.	Determine the 2D-DCT coefficients, Tk,l, k=0,1,2,3;l=0,1,2,3. 


In [19]:
def dct_matrix(n):
    W = [[(1 if b==0 else np.sqrt(2))*np.cos((2*a + 1)*b*np.pi/(2*n)) for a in range(n)] for b in range(n)]
    A = (W) / np.sqrt(n)

    return A
    

def dct_transform(x):
    dim = x.shape
    X = np.zeros(dim)
    A = dct_matrix(dim[0])
    X = np.matmul(A,x)
    X = np.matmul(X, A.T)
    
    return X

In [24]:
S = np.array([[9,1,9,1],[1,9,1,9],[9,1,9,1],[1,9,1,9]])
C = dct_transform(S)
print("2D-DCT of the image S")
print(C)
print()

C2 = dct(dct(S, type=2, norm='ortho', axis=0), type=2, norm='ortho', axis=1)
print("2D_DCT with scipy funtion:")
print(C2)
print()
##2.	Show that the reconstructed image from the original DFT coefficients equal to the original image.
print("Difference between the results: ")
print(np.abs(C2-C))
print("reconstructed image from the original DFT coefficients equal to the original image(by rounding to 5 decimal places  ))                                                       ")
print(np.around(np.abs(C2-C), decimals=5))


2D-DCT of the image S
[[ 2.00000000e+01  0.00000000e+00 -1.11022302e-15 -2.10942375e-15]
 [ 4.44089210e-16  2.34314575e+00  5.61935771e-16  5.65685425e+00]
 [-1.22124533e-15  2.97404770e-16  1.10933565e-31  7.17998630e-16]
 [-2.66453526e-15  5.65685425e+00  3.76480653e-16  1.36568542e+01]]

2D_DCT with scipy funtion:
[[20.          0.          0.          0.        ]
 [ 0.          2.34314575  0.          5.65685425]
 [ 0.          0.          0.          0.        ]
 [ 0.          5.65685425  0.         13.65685425]]

Difference between the results: 
[[7.10542736e-15 0.00000000e+00 1.11022302e-15 2.10942375e-15]
 [4.44089210e-16 0.00000000e+00 5.61935771e-16 0.00000000e+00]
 [1.22124533e-15 2.97404770e-16 1.10933565e-31 7.17998630e-16]
 [2.66453526e-15 8.88178420e-16 3.76480653e-16 5.32907052e-15]]
reconstructed image from the original DFT coefficients equal to the original image(by rounding to 5 decimal places  ))                                                       
[[0. 0. 0. 0.]
